### ISSUE TITLE
How to write a lang file?

### ISSUE THREAD

**Issue by dmmarmol** [dkesberg/slim-twig-translation-extension#1]
I've followed your instructions step by step and everything is working properly but... how the files inside `lang/' should be written, and which name syntax they need?

**Comment by dkesberg** [comment]
Hello, i am wrapping the translator class of the laravel framework (see documentation for more information http://laravel.com/docs/4.2/localization).

In the lang directory there should be a subdirectory for each language.

```
/lang
       /en
            mails.php
            messages.php
       /de
            mails.php
            messages.php
```

The language files simply return an array of keyed strings.

``` php
<?php

return array(
  'salutation' => array(
    'male'    => 'Dear Mr.',
    'female'  => 'Dear Mrs.',
    'unknown' => 'Dear Sir or Madam'
  )
)
```

In the templates files in the string you have to pass to the translate method the first part is the name of the language file and the second part is the name you want to retrieve.

``` php
{{ _('mails.salutation.male') }}
```

**Comment by dmmarmol** [comment]
This was very helpful and maybe you can place it in your README.md. 
One last question: I'm not an expert on php but how should i send that `'mails.salutation.male'` from the controller to a view without outputing as a string
Thank you very much!

**Comment by dmmarmol** [comment]
Sorry, i was so dumb that i forget to add the `_()`. My bad.
I'll close this issue and thank you again!

**Comment by dkesberg** [comment]
Hey, good suggestion i added my reply about the lang files to the README.md
